<?php if ( get_theme_mod('facebook', false) || get_theme_mod('twitter', false) || get_theme_mod('instagram', false) || get_theme_mod('pinterest', false) || get_theme_mod('googleplus', false) || get_theme_mod('behance', false) || get_theme_mod('deviantart', false) || get_theme_mod('dribbble', false) || get_theme_mod('flickr', false) || get_theme_mod('youtube', false) || get_theme_mod('vimeo', false) || get_theme_mod('github', false) || get_theme_mod('linkedin', false) || get_theme_mod('soundcloud', false) || get_theme_mod('reddit', false) || get_theme_mod('tumblr', false) || get_theme_mod('skype', false) || get_theme_mod('email', false) || get_theme_mod('meetup', false) ) : ?>
  <nav class="social">
    <ul>
      <?php $network = 'facebook'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'twitter'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'instagram'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'pinterest'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'googleplus'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'behance'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'deviantart'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'dribbble'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'flickr'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'youtube'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'vimeo'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'github'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'linkedin'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'soundcloud'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'reddit'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'tumblr'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'skype'; if(get_theme_mod($network, false)) : ?><li><a href="skype:<?php echo get_theme_mod($network, false); ?>?call" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'email'; if(get_theme_mod($network, false)) : ?><li><a href="mailto:<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>"><?php echo(ucwords($network)); ?></a></li><?php endif; ?>
      <?php $network = 'meetup'; if(get_theme_mod($network, false)) : ?><li><a href="<?php echo get_theme_mod($network, false); ?>" target="_blank" title="<?php echo(ucwords($network)); ?>"class="ico-<?php echo $network; ?>">
              <img src="<?php echo esc_url( get_stylesheet_directory_uri() ); ?>/images/social/ico-meetup.png"></a></li><?php endif; ?>
    </ul>
  </nav><!-- / social -->
<?php endif; ?>